background_b: 255
background_g: 86
background_r: 150
rosdistro: 'kinetic

  '
roslaunch:
  uris: {host_leopard_robotyka_ia_pw_edu_pl__37107: 'http://leopard.robotyka.ia.pw.edu.pl:37107/'}
rosversion: '1.12.7

  '
run_id: 98359d6a-07da-11e7-9584-ecb1d7602b67
